//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows;
using System.Windows.Media;
using System.Windows.Media.Effects;
using System.Windows.Media.Media3D;


namespace Daniellib.Util.Effects
{
	
	/// <summary>An effect that magnifies a circular region with a smooth boundary.</summary>
	public class SmoothMagnifyEffect : ShaderEffect {
		public static readonly DependencyProperty InputProperty = ShaderEffect.RegisterPixelShaderSamplerProperty("Input", typeof(SmoothMagnifyEffect), 0);
		public static readonly DependencyProperty CenterProperty = DependencyProperty.Register("Center", typeof(Point), typeof(SmoothMagnifyEffect), new UIPropertyMetadata(new Point(0.5D, 0.5D), PixelShaderConstantCallback(0)));
		public static readonly DependencyProperty InnerRadiusProperty = DependencyProperty.Register("InnerRadius", typeof(double), typeof(SmoothMagnifyEffect), new UIPropertyMetadata(((double)(0.2D)), PixelShaderConstantCallback(1)));
		public static readonly DependencyProperty OuterRadiusProperty = DependencyProperty.Register("OuterRadius", typeof(double), typeof(SmoothMagnifyEffect), new UIPropertyMetadata(((double)(0.4D)), PixelShaderConstantCallback(2)));
		public static readonly DependencyProperty MagnificationProperty = DependencyProperty.Register("Magnification", typeof(double), typeof(SmoothMagnifyEffect), new UIPropertyMetadata(((double)(2D)), PixelShaderConstantCallback(3)));
		public static readonly DependencyProperty AspectRatioProperty = DependencyProperty.Register("AspectRatio", typeof(double), typeof(SmoothMagnifyEffect), new UIPropertyMetadata(((double)(1.5D)), PixelShaderConstantCallback(4)));
		public SmoothMagnifyEffect() {
			PixelShader pixelShader = new PixelShader();
            pixelShader.UriSource = new Uri("/Daniellib.Util.Effects;component/effects/ps/SmoothMagnify.ps", UriKind.Relative);
			this.PixelShader = pixelShader;

			this.UpdateShaderValue(InputProperty);
			this.UpdateShaderValue(CenterProperty);
			this.UpdateShaderValue(InnerRadiusProperty);
			this.UpdateShaderValue(OuterRadiusProperty);
			this.UpdateShaderValue(MagnificationProperty);
			this.UpdateShaderValue(AspectRatioProperty);
		}
		public Brush Input {
			get {
				return ((Brush)(this.GetValue(InputProperty)));
			}
			set {
				this.SetValue(InputProperty, value);
			}
		}
		/// <summary>The center point of the magnified region.</summary>
		public Point Center {
			get {
				return ((Point)(this.GetValue(CenterProperty)));
			}
			set {
				this.SetValue(CenterProperty, value);
			}
		}
		/// <summary>The inner radius of the magnified region.</summary>
		public double InnerRadius {
			get {
				return ((double)(this.GetValue(InnerRadiusProperty)));
			}
			set {
				this.SetValue(InnerRadiusProperty, value);
			}
		}
		/// <summary>The outer radius of the magnified region.</summary>
		public double OuterRadius {
			get {
				return ((double)(this.GetValue(OuterRadiusProperty)));
			}
			set {
				this.SetValue(OuterRadiusProperty, value);
			}
		}
		/// <summary>The magnification factor.</summary>
		public double Magnification {
			get {
				return ((double)(this.GetValue(MagnificationProperty)));
			}
			set {
				this.SetValue(MagnificationProperty, value);
			}
		}
		/// <summary>The aspect ratio (width / height) of the input.</summary>
		public double AspectRatio {
			get {
				return ((double)(this.GetValue(AspectRatioProperty)));
			}
			set {
				this.SetValue(AspectRatioProperty, value);
			}
		}
	}
}
